# Generated by Django 5.0.3 on 2024-03-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexoadmin', '0002_hexo_blog_md_hexo_config_hexo_theme_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='hexo_theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(max_length=255)),
                ('theme_introduction', models.TextField()),
                ('theme_url', models.CharField(max_length=255)),
                ('theme_preview_url', models.CharField(max_length=255)),
                ('theme_install_command', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hexo_blog_md',
            name='loal_url',
        ),
    ]
