# Generated by Django 5.0.3 on 2024-03-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexoadmin', '0003_hexo_theme_remove_hexo_blog_md_loal_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hexo_theme',
            name='theme_install_command',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hexo_theme',
            name='theme_introduction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hexo_theme',
            name='theme_preview_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hexo_theme',
            name='theme_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
